[package]
name = "async-chat"
version = "0.1.0"
edition = "2021"
authors = ["Mateusz Nowak mats.nowak@hotmail.com"]
[dependencies]
async-std = "1.13.0"
serde = { version = "1.0.217", features = ["derive", "rc"] }
serde_json = "1.0.135"
tokio = { version = "1.43.0", features = ["sync"] }
